# Generated by Django 3.0.8 on 2020-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200718_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydiscussion',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
