# Generated by Django 3.0.8 on 2020-07-20 10:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200719_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.image_path),
        ),
    ]
